---
# Users
users:
  - name: kmet
    comment: 'Kevin MET'
    groups: admin
    shell: /bin/bash
    state: present
    ssh_key: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDch7PXOqVis44PiH6/WmfyukAAEpbNwv6Teh69mr3mgHSKQVEjawSxx/04R/zF4dK7DkTOF4F5w18Lf5e4T8i6uKxyyFfDn3kyo9aTm2wsJJ9Dd3bKTieqEPv+nm7W2ExZ1U+zE9WH5vxjn4eYHSgLjxcsk+hreY7dgqAeswVkzRpXutgZR6qVI4jR37zBXy6i9i+IFDV5veMWJf4GPx7VHgdfbzgUvfP+/LLs9uGf/l0KyLidwF5cMc9gKBJf0ta4xll/WqrsJWjDK6YAhzpnxmnUt5/bIsvZpPmoJk36oAh2wrPwYhXGogg5oygwh7/LB/N0dIg0rNE3LKjx+orqWWvFkHSII+rXpl4ulUFDhpmBTq8+w0jpIa2zh4JfByTtiogIfTSe/0zab8mokbbWuveNbmb2T/uKBoSb9Zhrba1GZbQxlT12q6eJdLFJypJACENBmEHgt67/m6ToJx62v+dkVcqrfaHWZ+F64P2JJ7NnucIWwLZo/Z6t2dqfCps= nierdz@precisux

# PHP
php_default_version_debian: "7.3"
php_packages:
  - php7.3-common
  - php7.3-cli
  - php7.3-dev
  - php7.3-fpm
  - libpcre3-dev
  - php7.3-gd
  - php7.3-curl
  - php7.3-imap
  - php7.3-json
  - php7.3-opcache
  - php7.3-xml
  - php7.3-mbstring
  - php-sqlite3
  - php-imagick

# Elasticsearch
es_ip_address: 46.105.122.24
kibana_server: data2.igln.fr

# BackupPC
backuppc_server: backup.atelierasap.com
