---
- name: Create /var/www/certbot directory
  file:
    path: /var/www/certbot
    state: directory
    owner: nginx
    group: nginx
    mode: 0755

- name: Remove default configuration
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify:
    - check nginx configuration
    - reload nginx

- name: Configure /etc/nginx/nginx.conf
  template:
    src: etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
    owner: root
    group: root
  notify:
    - check nginx configuration
    - reload nginx

- name: Better log rotation
  template:
    src: etc/logrotate.d/nginx.j2
    dest: /etc/logrotate.d/nginx
    owner: root
    group: root
    mode: 0644

- name: Create /var/backups/logs/nginx directory
  file:
    path: /var/backups/logs/nginx
    state: directory
    owner: www-data
    group: www-data
    mode: 0750

- name: Archive and delete nginx logs
  template:
    src: etc/cron.d/nginx.j2
    dest: /etc/cron.d/nginx
    owner: root
    group: root
    mode: 0644

- name: Check if /etc/nginx/dh4096.pem exists
  stat:
    path: /etc/nginx/dh4096.pem
  register: dh4096

- name: Create dh4096.pem
  command: /usr/bin/openssl dhparam -out /etc/nginx/dh4096.pem 4096
  when: not dh4096.stat.exists

- name: Create /etc/nginx/conf
  file:
    path: /etc/nginx/conf
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy all configuration files to /etc/nginx/conf/ directory
  template:
    src: "{{ item }}"
    dest: /etc/nginx/conf/{{ item | basename | regex_replace('\.j2','') }}
    owner: root
    group: root
    mode: 0644
  with_fileglob:
    - ../templates/etc/nginx/conf/*.j2
  notify:
    - check nginx configuration
    - reload nginx

- name: Create server-status configuration
  template:
    src: etc/nginx/conf.d/localhost.conf.j2
    dest: /etc/nginx/conf.d/localhost.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - check nginx configuration
    - reload nginx
