---
nextcloud_php_packages:
  - php-pear
  - php7.2-bz2
  - php7.2-curl
  - php7.2-gd
  - php7.2-json
  - php7.2-intl
  - php7.2-mbstring
  - php7.2-mysql
  - php7.2-zip
nextcloud_deploy_to: "/var/www/data.igln.fr"
nextcloud_domain: "data.igln.fr"
nextcloud_version_dir: "releases"
nextcloud_releases_path: "{{ nextcloud_deploy_to }}/{{ nextcloud_version_dir }}"
nextcloud_shared_path: "{{ nextcloud_deploy_to }}/shared"
nextcloud_current_dir: "current"
nextcloud_keep_releases: "60d"
nextcloud_shared_paths: []
nextcloud_shared_files:
  - config/config.php
nextcloud_git_repo: "https://github.com/nextcloud/server"
nextcloud_git_branch: "v16.0.1"
