---
- name: Cron restart
  ansible.builtin.service:
    name: cron
    state: restarted

- name: Apt update
  ansible.builtin.apt:
    update_cache: "true"
  register: cache_updated
  until: cache_updated is success
  retries: 10
  delay: 2

- name: Postfix restart
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: Restart backuppc
  delegate_to: "{{ backuppc_server }}"
  ansible.builtin.systemd:
    name: backuppc
    state: restarted

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
