---
- name: Modify /etc/apache2/conf-available/security.conf
  template: src=security.conf.j2 dest=/etc/apache2/conf-available/security.conf owner=root group=root mode=0644

- name: Check if security.conf is activated
  stat: path=/etc/apache2/conf-enabled/security.conf
  register: security_conf

- name: Activate security.conf if needed
  when: security_conf.stat.exists == False
  shell: a2enconf security.conf

- name: Create /etc/apache2/ssl path if needed 
  file: path=/etc/apache2/ssl state=directory owner=root group=root mode=0755

- name: Add security-ssl.conf file
  template: src=security-ssl.conf.j2 dest=/etc/apache2/conf-available/security-ssl.conf owner=root group=root mode=0644

- name: Check if security-ssl.conf is activated
  stat: path=/etc/apache2/conf-enabled/security-ssl.conf
  register: security_ssl_conf

- name: Activate security-ssl.conf if needed
  when: security_ssl_conf.stat.exists == False
  shell: a2enconf security-ssl.conf

- name: Add proper logrotate with date
  template: src=logrotate.apache.j2 dest=/etc/logrotate.d/apache2 owner=root group=root mode=0644

- name: Create /home/backup/log/apache2 directory
  file: path=/home/backup/log/apache2 state=directory owner=www-data group=www-data mode=750

- name: Add apache logs archive and delete to crontab
  blockinfile:
    dest: /etc/crontab
    marker: "# {mark} ANSIBLE : Apache logs archive and delete"
    create: yes
    block: |
      00 4	* * *	root	find /var/log/apache2 -mtime +7 -exec mv {} /home/backup/log/apache2/ \;
      00 5	* * *	root	find /home/backup/log/apache2 -type f -name *.gz -mtime +365 -exec /bin/rm {} \;
  notify:
    - restart cron

- name: Check if /etc/apache2/ssl/dh4096.pem exists
  stat: path=/etc/apache2/ssl/dh4096.pem
  register: dh4096

- name: Create dh4096.pem
  when: dh4096.stat.exists == False
  shell: openssl dhparam -out /etc/apache2/ssl/dh4096.pem 4096
  register: result
  failed_when: "result.rc != 0"

- name: Create /etc/apache2/conf path if needed
  file: path=/etc/apache2/conf state=directory owner=root group=root mode=0755

- name: Add expires.conf in /etc/apache2/conf
  template: src=expires.conf.j2 dest=/etc/apache2/conf/expires.conf owner=root group=root mode=0644

- name: Activate several modules
  shell: "{{ item }}"
  with_items:
    - a2enmod rewrite
    - a2enmod expires
    - a2enmod deflate
    - a2enmod proxy
    - a2enmod proxy_fcgi
    - a2enmod ssl
    - a2enmod headers
