---
- name: Check if default vhost is active
  stat: path=/etc/apache2/sites-enabled/000-default.conf
  register: default_vhost

- name: Disable default vhost if needed
  when: default_vhost.stat.exists == True
  shell: a2dissite 000-default.conf
  register: result
  failed_when: "result.rc != 0"

- name: Delete default vhost
  file: path=/etc/apache2/sites-available/000-default.conf state=absent

- name: Delete default SSL vhost
  file: path=/etc/apache2/sites-available/default-ssl.conf state=absent

- name: Create users if needed
  when: item.value.user != 'www-data'
  user: name={{ item.value.user }} password={{ lookup('password', 'passwords/' + mnttech_fqdn + '/user_{{ item.value.user }}_password.txt encrypt=md5_crypt') }} groups=www-data
  with_dict: "{{ apache_vhosts }}"

- name: Add www-data to user group if needed
  when: item.value.user != 'www-data'
  shell: usermod -a -G {{ item.value.user }} www-data
  with_dict: "{{ apache_vhosts }}"

- name: Create web root directory if needed
  when: item.value.root is defined
  file: path={{ item.value.root }} state=directory owner={{ item.value.user }} group={{ item.value.user }} mode=0755
  with_dict: "{{ apache_vhosts }}"

- name: Add vhosts to sites-available folder
  template: src=vhost.conf.j2 dest=/etc/apache2/sites-available/{{ item }}.conf owner=root group=root mode=0644
  with_items: "{{ apache_vhosts | list }}"
  register: vhosts

- name: Push SSLCertificateFile file in ssl folder if needed
  when: item.value.SSLCertificateFile is defined and item.value.certbot is not defined
  copy: src=ssl/{{ item.value.SSLCertificateFile }} dest=/etc/apache2/ssl/{{ item.value.SSLCertificateFile }} owner=root group=root mode=0640
  with_dict: "{{ apache_vhosts }}"

- name: Push SSLCertificateKeyFile file in ssl folder if needed
  when: item.value.SSLCertificateKeyFile is defined and item.value.certbot is not defined
  copy: src=ssl/{{ item.value.SSLCertificateKeyFile }} dest=/etc/apache2/ssl/{{ item.value.SSLCertificateKeyFile }} owner=root group=root mode=0640
  with_dict: "{{ apache_vhosts }}"

- name: Push SSLCACertificateFile file in ssl folder if needed
  when: item.value.SSLCACertificateFile is defined and item.value.certbot is not defined
  copy: src=ssl/{{ item.value.SSLCACertificateFile }} dest=/etc/apache2/ssl/{{ item.value.SSLCACertificateFile }} owner=root group=root mode=0640
  with_dict: "{{ apache_vhosts }}"

- name: Activate all vhosts
  when: vhosts.changed
  shell: a2ensite {{ item.key }}.conf
  register: result
  failed_when: "result.rc != 0"
  with_dict: "{{ apache_vhosts }}"
  notify:
    - check apache configuration
    - reload apache
