---
sudo: required
language: generic
python: 3.8
addons:
  apt:
    update: true
    packages:
      - python3-pip

before_install:
  - make install

script:
  - make travis-lint

env:
  global:
    - secure: "SFJEVdWCktET/gtESTsbxn4aJVXSLRvv70JN4LuTgxOThj3xCRxkIb/2W90Opn6DQy3pne9XhL5zulCc6O4gE8HO6loWNXzWSrAAud2AZ0PrTT6Oqw6vRno1ZYQSCqF1M1tLbvLdGOuwenRvIr2kpDYpbTfitLihsUyRAgvBw9m5vRpwv42uit+XaM4ZnVjeqD483H+esI4VJDY/Juou1a9w4WV5ZlG+AZpjIgz4EICt5x0HthUcrTGDFeBAjT58y8+MSpN1tgiw5LwD+fG2elUCXnAmDiMKmhATNJmpUnKuDL4AORsofxPiWxhg5Z2F2dTuWBey1jl/jeNFyS9jIgkb0J69NV8rlHb5b4/J2ETjjKuRhQS5ONUEAAgTpre5jKBJPP88QUKaLZJNTmxUea7BEBBJtSosXf9nD9IhRQVXfci9dA5X68GM0m+U+V2ho+txUf7EfdCPQT/9wsrqk0iTAWcfkojEirmW0I8Hg+tZDHooQp0YMDG/dE/lz2qDQi+AJ4IA9BEjjb0QKAqpmPMRzSlIUHYhrJJ4hCGAXwq4XG1SRCFiWg4HqDgevtX0ymX3dUm6l43ciJ7v2hNW1zrCOl0nRyBJ5Dm+lHEaZbn5XGbSKIdAn5gEq/bgkH39WlJwWUl94NlwHV15jRMjSsE3UJ7eb/sNUMOpc+IEFnw="
