version: '3'

networks:
  mnttech-network:

services:
  mnttech:
    container_name: mnttech
    image: nginx:1.19
    restart: always
    ports:
      - ${MNTTECH_IP}:80:80
      - ${MNTTECH_IP}:443:443
    volumes:
      - ./mnt-tech.fr:/mnt-tech.fr:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf:ro
      - ./nginx/mnttech.conf.d/:/etc/nginx/conf.d:ro
      - /root/.acme.sh/mnt-tech.fr/:/etc/nginx/mnt-tech.fr:ro
    networks:
      - mnttech-network
