version: '3'

services:
  valc-mysql:
    container_name: valc-mysql
    image: nierdz/mysql:1.1.11
    restart: always
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --general_log=1
      --general_log_file=/var/lib/mysql/general.log
    volumes:
      - /opt/valc/mysql:/var/lib/mysql:rw
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -u root -p${MYSQL_ROOT_PASSWORD} ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  valc-wordpress:
    container_name: valc-wordpress
    image: nierdz/videoalacon.fr:1.4.1
    restart: on-failure
    ports:
      - ${VALC_HTTPS_PORT}:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf:ro
      - ./nginx/valc.conf.d/:/etc/nginx/conf.d:ro
      - /var/log/nginx/:/var/log/nginx/:rw
      - ./php/zzz-hardening.ini:/usr/local/etc/php/conf.d/zzz-hardening.ini
      - ./php/zzz-opcache.ini:/usr/local/etc/php/conf.d/zzz-opcache.ini
      - ./php/zzz-php-fpm-tuning.conf:/usr/local/etc/php-fpm.d/zzz-php-fpm-tuning.conf
      - /root/.acme.sh/videoalacon.fr_ecc/:/etc/nginx/videoalacon.fr:ro
      - /opt/valc/images:/var/www/bedrock/web/images:ro
      - /opt/valc/uploads:/var/www/bedrock/web/app/uploads:rw
      - .env:/var/www/bedrock/.env:ro
      - ./matomo/config.ini.php:/var/www/matomo/config/config.ini.php:ro
    shm_size: 512M
    depends_on:
      - valc-mysql
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://127.0.0.1:80/fpm-status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
