version: '3'

services:
  igln:
    container_name: igln
    image: nierdz/igln.fr:2.0.2
    restart: always
    ports:
      - ${IGLN_HTTPS_PORT}:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf:ro
      - ./nginx/igln.conf.d/:/etc/nginx/conf.d:ro
      - /root/.acme.sh/igln.fr/:/etc/nginx/igln.fr:ro
      - /root/.acme.sh/mnt-tech.fr/:/etc/nginx/mnt-tech.fr:ro
