version: '3'

networks:
  mnttech-network:

services:
  mnttech-nginx:
    container_name: mnttech-nginx
    image: nginx:1.19
    restart: always
    ports:
      - ${MNTTECH_IP}:80:80
      - ${MNTTECH_IP}:443:443
    volumes:
      - ./mnttech/www:/mnttech/www:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf:ro
      - ./nginx/mnttech.conf.d/:/etc/nginx/conf.d:ro
      - /root/.acme.sh/mnt-tech.fr/:/etc/nginx/mnt-tech.fr:ro
    depends_on:
      - mnttech-php-fpm
    networks:
      - mnttech-network

  mnttech-php-fpm:
    container_name: mnttech-php-fpm
    image: php:7.4-fpm
    restart: always
    volumes:
      - ./mnttech/www:/mnttech/www:ro
    networks:
      - mnttech-network
