version: '3'

services:
  madrabbit-mysql:
    container_name: madrabbit-mysql
    image: nierdz/mysql:1.1.8
    restart: always
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --general_log=1
      --general_log_file=/var/lib/mysql/general.log
    volumes:
      - /opt/madrabbit-mysql:/var/lib/mysql:rw
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -u root -p${MYSQL_ROOT_PASSWORD} ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  madrabbit-wordpress:
    container_name: madrabbit-wordpress
    image: nierdz/mad-rabbit.com:1.1.2
    restart: on-failure
    ports:
      - ${MADRABBIT_HTTPS_PORT}:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf:ro
      - ./nginx/madrabbit.conf.d/:/etc/nginx/conf.d:ro
      - ./php/zzz-hardening.ini:/usr/local/etc/php/conf.d/zzz-hardening.ini
      - ./php/zzz-opcache.ini:/usr/local/etc/php/conf.d/zzz-opcache.ini
      - ./php/zzz-php-fpm-tuning.conf:/usr/local/etc/php-fpm.d/zzz-php-fpm-tuning.conf
      - /root/.acme.sh/mad-rabbit.com/:/etc/nginx/mad-rabbit.com:ro
      - ./madrabbit/images:/var/www/bedrock/web/images:ro
      - ./madrabbit/uploads:/var/www/bedrock/web/app/uploads:rw
      - .env:/var/www/bedrock/.env:ro
    depends_on:
      - madrabbit-mysql
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://127.0.0.1:80/fpm-status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
