version: '3'
# TODO: 
#  all container logs on stdout/stderr
#  add healthcheck on all services
#  nginx hardening
#  php-fpm hardening
#  add git submodule for other projects
#  add webminerpool
#  include ssl config and maybe other configs instead of duplicate code

networks:
  adplusplus-network:

services:
  adplusplus-nginx:
    container_name: adplusplus-nginx
    image: nginx:1.15.3
    restart: always
    ports:
        - "145.239.217.56:80:80"
        - "145.239.217.56:443:443"
    volumes:
      - ./adplusplus/www:/adplusplus/www:ro
      - ./adplusplus/conf:/adplusplus/conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/adplusplus.conf.d/:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - adplusplus-php-fpm
    networks:
      - adplusplus-network

  adplusplus-percona:
    container_name: adplusplus-percona
    build:
      context: ./adplusplus-percona
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always
    volumes:
      - /opt/adplusplus-percona:/var/lib/mysql:rw
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    networks:
      - adplusplus-network

  adplusplus-php-fpm:
    container_name: adplusplus-php-fpm
    build: ./adplusplus-php-fpm
    restart: always
    volumes:
      - ./adplusplus/www:/adplusplus/www:ro
    environment:
      - REDIS_HOST
    depends_on:
      - adplusplus-redis
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - adplusplus-network

  adplusplus-redis:
    container_name: adplusplus-redis
    image: redis:4.0.11
    restart: always
    volumes:
      - /opt/adplusplus-redis:/data:rw
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - adplusplus-network
