version: '3'

networks:
  igln-network:

services:
  igln-hugo:
    container_name: igln-hugo
    build:
      context: ./igln.fr
    restart: always
    ports:
      - ${IGLN_IP}:80:80
      - ${IGLN_IP}:443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf:ro
      - ./nginx/igln.conf.d/:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - igln-network
