version: '3'

networks:
  igln-network:

services:
  igln:
    container_name: igln
    image: nierdz/igln.fr:1.0.11
    restart: always
    ports:
      - ${IGLN_IP}:80:80
      - ${IGLN_IP}:443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf:ro
      - ./nginx/igln.conf.d/:/etc/nginx/conf.d:ro
      - /root/.acme.sh/igln.fr/:/etc/nginx/igln.fr:ro
    networks:
      - igln-network
