version: '3'

networks:
  madrabbit-network:

services:
  madrabbit-nginx:
    container_name: madrabbit-nginx
    image: nginx:1.21
    restart: always
    ports:
      - ${MADRABBIT_IP}:80:80
      - ${MADRABBIT_IP}:443:443
    volumes:
      - ./madrabbit/www:/madrabbit/www:ro
      - ./madrabbit/media:/madrabbit/media:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf:ro
      - ./nginx/madrabbit.conf.d/:/etc/nginx/conf.d:ro
      - /root/.acme.sh/mad-rabbit.com/:/etc/nginx/mad-rabbit.com:ro
    depends_on:
      - madrabbit-php-fpm
    networks:
      - madrabbit-network

  madrabbit-mysql:
    container_name: madrabbit-mysql
    image: nierdz/mysql:1.1.6
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - /opt/madrabbit-mysql:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MADRABBIT_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MADRABBIT_MYSQL_DATABASE}
      MYSQL_USER: ${MADRABBIT_MYSQL_USER}
      MYSQL_PASSWORD: ${MADRABBIT_MYSQL_PASSWORD}
    networks:
      - madrabbit-network

  madrabbit-php-fpm:
    container_name: madrabbit-php-fpm
    image: nierdz/php-fpm-7.4:1.0.6
    restart: always
    volumes:
      - ./madrabbit/www:/madrabbit/www:rw
      - ./madrabbit/media:/madrabbit/media:rw
    environment:
      - MADRABBIT_MYSQL_DATABASE
      - MADRABBIT_MYSQL_USER
      - MADRABBIT_MYSQL_PASSWORD
    depends_on:
      - madrabbit-mysql
    networks:
      - madrabbit-network
