version: '3'

networks:
  adplusplus-network:

services:
  adplusplus-nginx:
    container_name: adplusplus-nginx
    image: nginx:1.17
    restart: always
    ports:
      - ${ADPLUSPLUS_IP}:80:80
      - ${ADPLUSPLUS_IP}:443:443
    volumes:
      - ./adplusplus/www:/adplusplus/www:ro
      - ./adplusplus/conf:/adplusplus/conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf:ro
      - ./nginx/adplusplus.conf.d/:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot:/var/www/certbot:rw
    depends_on:
      - adplusplus-php-fpm
    networks:
      - adplusplus-network

  adplusplus-php-fpm:
    container_name: adplusplus-php-fpm
    build: ./docker/php-fpm-7.3
    restart: always
    volumes:
      - ./adplusplus/www:/adplusplus/www:ro
    networks:
      - adplusplus-network

  adplusplus-webminer:
    container_name: adplusplus-webminer
    image: adplusplus-webminer:1.0
    build:
      context: ./webminerpool
      args:
        - DONATION_LEVEL=${WEBMINER_DONATION_LEVEL}
    restart: always
    ports:
      - ${WEBMINER_IP}:80:80
      - ${WEBMINER_IP}:8181:8181
    environment:
      DOMAIN: ${WEBMINER_DOMAIN}
    networks:
      - adplusplus-network
