- name: Provision all servers
  hosts: all
  roles:
    - { role: utils, tags: ['utils'] }

- name: Provision xmr-stak
  hosts: xmr-stak
  roles:
    - { role: xmr-stak, tags: ['xmr-stak'] }

- name: Configure ip failover
  hosts: physical
  roles:
    - { role: ip-failover, tags: ['ip-failover'] }
