- name: Provision all servers
  become: true
  hosts: all
  roles:
    - { role: utils, tags: ['utils'] }
    - { role: bind, tags: ['bind'] }
  post_tasks:
    - name: Remove /etc/sudoers.d/kmet
      file:
        path: /etc/sudoers.d/kmet
        state: absent
    # use this ugly hack cause meta: reset_connection does not work
    - name: Remove local control_path to force login again to load group
      local_action: # noqa 504
        module: file
        path: /home/{{ ansible_user }}/.ssh/{{ ansible_env.SUDO_USER }}@{{ inventory_hostname }}:22
        state: absent

- name: Provision xmr-stak
  become: true
  hosts: xmrstak
  roles:
    - { role: xmr-stak, tags: ['xmr-stak'] }

- name: Provision hypervisors
  become: true
  hosts: hv
  pre_tasks:
    - name: Install minicrypt
      unarchive:
        src: minicrypt.tar.gz
        dest: /opt
  roles:
    - { role: docker, tags: ['docker'] }

- name: Configure ip failover
  become: true
  hosts: physical
  roles:
    - { role: ip-failover, tags: ['ip-failover'] }

- name: Configure nextcloud servers
  become: true
  hosts: data
  vars_files:
    - vault_vars/data.yml
    - vault_vars/all.yml
  # First nginx will only create a vhost for certbot
  # Then, second one will create actual vhost
  roles:
    - { role: nginx, tags: ['nginx'], dummy: 'first' }
    - { role: certbot, tags: ['certbot'] }
    - { role: nginx, tags: ['nginx'], dummy: 'second' }
    - { role: mysql, tags: ['mysql'] }
    - { role: php, tags: ['php'] }
    - { role: percona, tags: ['percona'] }
    - { role: nextcloud, tags: ['nextcloud'] }
  pre_tasks:
    - name: Install sury key
      apt_key:
        url: "https://packages.sury.org/php/apt.gpg"
        state: present
    - name: Add sury repositories
      apt_repository:
        repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes
        filename: 'sury'

- name: Provision transmission
  become: true
  hosts: data1.igln.fr
  vars_files:
    - vault_vars/transmission.yml
  roles:
    - { role: transmission, tags: ['transmission'] }
