- name: Provision all servers
  become: true
  hosts: all
  roles:
    - { role: utils, tags: ['utils'] }
    - { role: bind, tags: ['bind'] }
  post_tasks:
    - name: Remove /etc/sudoers.d/kmet
      file:
        path: /etc/sudoers.d/kmet
        state: absent

- name: Provision xmr-stak
  become: true
  hosts: xmrstak
  roles:
    - { role: xmr-stak, tags: ['xmr-stak'] }

- name: Provision hypervisors
  become: true
  hosts: hv
  pre_tasks:
    - name: Install minicrypt
      unarchive:
        src: minicrypt.tar.gz
        dest: /opt
  roles:
    - { role: docker, tags: ['docker'] }

- name: Configure ip failover
  become: true
  hosts: physical
  roles:
    - { role: ip-failover, tags: ['ip-failover'] }

- name: Configure nextcloud servers
  become: true
  hosts: data
  vars_files:
    - vault_vars/data.yml
    - vault_vars/all.yml
  # First nginx will only create a vhost for certbot
  # Then, second one will create actual vhost
  roles:
    - { role: nginx, tags: ['nginx'], dummy: 'first' }
    - { role: certbot, tags: ['certbot'] }
    - { role: nginx, tags: ['nginx'], dummy: 'second' }
    - { role: mysql, tags: ['mysql'] }
    - { role: percona, tags: ['percona'] }
