- name: Provision all servers
  hosts: all
  roles:
    - { role: utils, tags: ['utils'] }
    - { role: bind, tags: ['bind'] }

- name: Provision xmr-stak
  hosts: xmr-stak
  roles:
    - { role: xmr-stak, tags: ['xmr-stak'] }

- name: Provision docker
  hosts: hv
  roles:
    - { role: docker, tags: ['docker'] }

- name: Configure ip failover
  hosts: physical
  roles:
    - { role: ip-failover, tags: ['ip-failover'] }
