- name: Provision all servers
  hosts: all
  roles:
    - { role: utils, tags: ['utils'] }
    - { role: bind, tags: ['bind'] }

- name: Provision xmr-stak
  hosts: xmr-stak
  roles:
    - { role: xmr-stak, tags: ['xmr-stak'] }

- name: Provision hypervisors
  hosts: hv
  pre_tasks:
    - name: Install minicrypt
      unarchive:
        src: minicrypt.tar.gz
        dest: /opt
  roles:
    - { role: docker, tags: ['docker'] }

- name: Configure ip failover
  hosts: physical
  roles:
    - { role: ip-failover, tags: ['ip-failover'] }

- name: Configure nextcloud servers
  hosts: data
  roles:
    - { role: apache-php-fpm, tags: ['apache-php-fpm'] }
