---
- src: https://github.com/geerlingguy/ansible-role-php
  version: 3.7.0
  name: php

- src: https://github.com/geerlingguy/ansible-role-mysql
  version: 2.9.4
  name: mysql

- src: https://github.com/ansistrano/deploy
  version: 3.1.0
  name: deploy

- src: https://github.com/ansistrano/rollback
  version: 2.0.0
  name: rollback
