---
- src: https://github.com/geerlingguy/ansible-role-php
  version: 3.7.0
  name: php

- src: https://github.com/geerlingguy/ansible-role-mysql
  version: 2.9.5
  name: mysql

- src: https://github.com/elastic/ansible-elasticsearch
  version: 7.4.1
  name: elasticsearch

- src: https://github.com/nierdz/ansible-role-docker
  version: v1.0.3
  name: docker

- src: https://github.com/nierdz/ansible-role-nginx
  version: v1.1.0
  name: nginx
