---
- src: https://github.com/geerlingguy/ansible-role-nginx
  version: 2.6.3
  name: nginx

- src: https://github.com/geerlingguy/ansible-role-php
  version: 3.7.0
  name: php

- src: https://github.com/geerlingguy/ansible-role-mysql
  version: 2.9.4
  name: mysql
