---
- src: https://github.com/geerlingguy/ansible-role-php
  version: 4.5.1
  name: php

- src: https://github.com/geerlingguy/ansible-role-mysql
  version: 3.3.0
  name: mysql

- src: https://github.com/nierdz/ansible-role-docker
  version: v1.0.5
  name: docker

- src: https://github.com/nierdz/ansible-role-nginx
  version: v1.1.2
  name: nginx
