---
- src: https://github.com/geerlingguy/ansible-role-php
  version: 3.7.0
  name: php

- src: https://github.com/geerlingguy/ansible-role-mysql
  version: 2.9.4
  name: mysql

- src: https://github.com/elastic/ansible-elasticsearch
  version: 7.1.1
  name: elasticsearch

- src: https://github.com/geerlingguy/ansible-role-java
  version: 1.9.5
  name: java
