---
- name: Configure ip failover
  template:
    src: etc/network/interfaces.d/sys-failover.cfg.j2
    dest: /etc/network/interfaces.d/sys-failover.cfg
  notify: restart networking
  when: ip_failover is defined
