---
# Docker
docker_install_compose_plugin: true

# Nextcloud
nextcloud_domain: "data.igln.fr"
nextcloud_admin_user: "{{ nextcloud_admin_user_vault }}"
nextcloud_admin_password: "{{ nextcloud_admin_password_vault }}"
nextcloud_instanceid: "{{ nextcloud_instanceid_vault }}"
nextcloud_passwordsalt: "{{ nextcloud_passwordsalt_vault }}"
nextcloud_secret: "{{ nextcloud_secret_vault }}"
nextcloud_dbpassword: "{{ nextcloud_dbpassword_vault }}"

# MySQL
mysql_root_password: "{{ mysql_root_password_vault }}"
mysql_bind_address: 127.0.0.1
mysql_packages:
  - mariadb-client
  - mariadb-server
  - python3-mysqldb
mysql_databases:
  - name: nextcloud
    encoding: utf8mb4
    collation: utf8mb4_general_ci
mysql_users:
  - name: nextcloud
    host: "localhost"
    password: "{{ nextcloud_dbpassword }}"
    priv: "nextcloud.*:ALL"
    state: present

# Crontabs
crontabs:
  mysql backup:
    user: root
    state: present
    job: /usr/local/bin/mysql_backup.sh
    minute: 00
    hour: 1

# Acme.sh
acme_sh_certificates:
  - domains:
      - videoalacon.fr
      - www.videoalacon.fr
      - stats.videoalacon.fr
      - mad-rabbit.com
      - www.mad-rabbit.com
      - tenminutestokill.com
      - www.tenminutestokill.com
      - igln.fr
      - www.igln.fr
      - mnt-tech.fr
      - www.mnt-tech.fr
    renew_hook: "systemctl restart nginx && systemctl restart docker-compose@valc"
  - domains:
      - "{{ nextcloud_domain }}"
    renew_hook: "systemctl restart nginx"

# Nginx
nginx_remove_default_vhost: true
nginx_service_enabled: true
nginx_service_state: started
nginx_listen_ipv6: false
nginx_vhosts:
  - listen: "*:443 ssl http2 "
    server_name: videoalacon.fr www.videoalacon.fr stats.videoalacon.fr mad-rabbit.com www.mad-rabbit.com tenminutestokill.com www.tenminutestokill.com igln.fr www.igln.fr mnt-tech.fr www.mnt-tech.fr
    state: present
    extra_parameters: |
      ssl_certificate /root/.acme.sh/videoalacon.fr_ecc/fullchain.cer;
      ssl_certificate_key /root/.acme.sh/videoalacon.fr_ecc/videoalacon.fr.key;
      include /etc/nginx/generic.conf;
      include /etc/nginx/gzip.conf;
      include /etc/nginx/security.conf;
      include /etc/nginx/ssl.conf;

      location / {
        proxy_pass https://localhost:4430;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
      }
  - listen: "*:443 ssl http2 default_server"
    server_name: "{{ nextcloud_domain }}"
    state: present
    root: "/var/www/{{ nextcloud_domain }}/current/nextcloud"
    index: index.php index.html /index.php$request_uri
    extra_parameters: |
      ssl_certificate /root/.acme.sh/{{ nextcloud_domain }}_ecc/fullchain.cer;
      ssl_certificate_key /root/.acme.sh/{{ nextcloud_domain }}_ecc/{{ nextcloud_domain }}.key;
      include /etc/nginx/generic.conf;
      include /etc/nginx/gzip.conf;
      include /etc/nginx/security.conf;
      include /etc/nginx/ssl.conf;
      add_header X-Robots-Tag "none" always;

      location ^~ /.well-known {
        location = /.well-known/carddav { return 301 /remote.php/dav/; }
        location = /.well-known/caldav { return 301 /remote.php/dav/; }
        location /.well-known/acme-challenge { try_files $uri $uri/ =404; }
        location /.well-known/pki-validation { try_files $uri $uri/ =404; }
        return 301 /index.php$request_uri;
      }

      client_max_body_size 512M;
      fastcgi_buffers 64 4K;

      location /remote {
        return 301 /remote.php$request_uri;
      }

      location / {
        try_files $uri $uri/ /index.php$request_uri;
      }


      location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)(?:$|/) { return 404; }
      location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) { return 404; }

      location ~ \.php(?:$|/) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        set $path_info $fastcgi_path_info;

        try_files $fastcgi_script_name =404;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $path_info;
        fastcgi_param HTTPS on;

        fastcgi_param modHeadersAvailable true;
        fastcgi_param front_controller_active true;
        fastcgi_pass 127.0.0.1:9000;

        fastcgi_intercept_errors on;
        fastcgi_request_buffering off;
      }

# PHP
php_default_version_debian: "8.2"
php_packages:
  - php8.2-cli
  - php8.2-fpm
php_install_recommends: false
php_enable_webserver: false
php_enable_php_fpm: true
php_enable_apc: false
php_memory_limit: "512M"
php_upload_max_filesize: "512M"
php_post_max_size: "512M"
php_date_timezone: "Europe/Paris"
php_opcache_zend_extension: "opcache.so"
php_opcache_enable: "1"
php_opcache_enable_cli: "0"
php_opcache_memory_consumption: "128"
php_opcache_interned_strings_buffer: "16"
php_opcache_max_accelerated_files: "10000"
php_opcache_max_wasted_percentage: "5"
php_opcache_validate_timestamps: "0"
php_opcache_revalidate_path: "0"
php_opcache_revalidate_freq: "1"
php_opcache_max_file_size: "0"

# Logrotate
logrotate_options:
  - weekly
  - rotate 4
  - create
  - dateext

logrotate_applications:
  - name: nginx
    definitions:
      - logs:
          - /var/log/nginx/*.log
        options:
          - daily
          - missingok
          - rotate 180
          - compress
          - delaycompress
          - notifempty
          - create 0644 www-data adm
          - sharedscripts
          - dateext
          - dateformat .%Y-%m-%d
        postrotate:
          - /usr/bin/kill -USR1 "$(cat /run/nginx.pid)"
          - /usr/bin/systemctl restart docker-compose@valc
