---
- name: check apache configuration
  shell: "apachectl -t"
  register: result
  failed_when: "result.rc != 0"

- name: restart apache
  service: name=apache2 state=restarted

- name: reload apache
  service: name=apache2 state=reloaded
