---
- name: Clone acme.sh repository
  git:
    repo: https://github.com/acmesh-official/acme.sh.git
    version: "{{ acme_sh_version }}"
    dest: "{{ acme_sh_path }}"

- name: Create certificates
  shell: source /infra/.ovh && ./acme.sh --issue -d {{ item.domains | join(' -d ') }} --renew-hook "{{ item.renew_hook }}" --dns dns_ovh
  args:
    creates: /root/.acme.sh/{{ item.domains | first }}/{{ item.domains | first }}.conf
    chdir: "{{ acme_sh_path }}"
    executable: /bin/bash
  loop: "{{ acme_sh_certificates }}"

- name: Create cron entry to renew certificates
  cron:
    name: "Renew certificates"
    minute: "0"
    hour: "5"
    job: "source /infra/.ovh && {{ acme_sh_path }}/acme.sh --cron --syslog 6"
