---
- name: Add nagios IP in /etc/nagios/nrpe.cfg
  lineinfile:
    dest: /etc/nagios/nrpe.cfg
    regexp: '^allowed_hosts=.*'
    line: 'allowed_hosts=127.0.0.1,{{ nagios_ip }}'
  notify:
    - restart nrpe

- name: Set command_timeout in /etc/nagios/nrpe.cfg
  lineinfile:
    dest: /etc/nagios/nrpe.cfg
    regexp: '^command_timeout=.*'
    line: 'command_timeout=600'
  notify:
    - restart nrpe

- name: Set connection_timeout in /etc/nagios/nrpe.cfg
  lineinfile:
    dest: /etc/nagios/nrpe.cfg
    regexp: '^connection_timeout=.*'
    line: 'connection_timeout=600'
  notify:
    - restart nrpe

- name: Add check_multiprocs to /usr/lib/nagios/plugins/ folder
  template: src=check_multiprocs.j2 dest=/usr/lib/nagios/plugins/check_multiprocs owner=root group=root mode=0755

- name: Add check_redis.pl to /usr/lib/nagios/plugins folder 
  template: src=check_redis.j2 dest=/usr/lib/nagios/plugins/check_redis.pl owner=root group=root mode=0755

- name: Add multiprocs.list file
  template: src=multiprocs.list.j2 dest=/etc/nagios/multiprocs.list owner=root group=root mode=0644 force=no

- name: Write basic commands to /etc/nagios/nrpe_local.cfg
  lineinfile: dest=/etc/nagios/nrpe_local.cfg regexp={{ item.regexp }} line={{ item.line }}
  with_items:
    - { regexp: '^command\[check_users\]=.*check_users -w [0-9]+ -c [0-9]+', line: 'command[check_users]=/usr/lib/nagios/plugins/check_users -w {{ check_users.warning }} -c {{ check_users.critical }}' }
    - { regexp: '^command\[check_load\]=.*check_load -w [0-9]+,[0-9]+,[0-9]+ -c [0-9]+,[0-9]+,[0-9]+', line: 'command[check_load]=/usr/lib/nagios/plugins/check_load -w {{ check_load.warning }} -c {{ check_load.critical }}' }
    - { regexp: '^command\[check_multiprocs\]=.*check_multiprocs -c /etc/nagios/multiprocs.list', line: 'command[check_multiprocs]=/usr/lib/nagios/plugins/check_multiprocs -c /etc/nagios/multiprocs.list' }
    - { regexp: '^command\[check_zombie_procs\]=/usr/lib/nagios/plugins/check_procs -w [0-9]+ -c [0-9]+ -s Z', line: 'command[check_zombie_procs]=/usr/lib/nagios/plugins/check_procs -w {{ check_zombie_procs.warning }} -c {{ check_zombie_procs.critical }} -s Z' }
    - { regexp: '^command\[check_total_procs\]=.*check_procs -w [0-9]+ -c [0-9]+', line: 'command[check_total_procs]=/usr/lib/nagios/plugins/check_procs -w {{ check_total_procs.warning }} -c {{ check_total_procs.critical }}' }
    - { regexp: '^command\[check_swap\]=.*check_swap -w [0-9]+% -c [0-9]+%', line: 'command[check_swap]=/usr/lib/nagios/plugins/check_swap -w {{ check_swap.warning }}% -c {{ check_swap.critical }}%' }
    - { regexp: '^command\[check_memory\]=.*check_memory -w [0-9]+% -c [0-9]+%', line: 'command[check_memory]=/usr/lib/nagios/plugins/check_memory -w {{ check_memory.warning }}% -c {{ check_memory.critical }}%' }
    - { regexp: '^command\[check_mailq\]=.*check_mailq -w [0-9]+ -c [0-9]+', line: 'command[check_mailq]=/usr/lib/nagios/plugins/check_mailq -w {{ check_mailq.warning }} -c {{ check_mailq.critical }}' }
  notify:
    - restart nrpe

- name: Write check_disk commands to /etc/nagios/nrpe_local.cfg
  lineinfile:
    dest: /etc/nagios/nrpe_local.cfg
    regexp: '^command\[check{{ item.key }}_disk\]=.*check_disk -w [0-9]+% -c [0-9]+% -p /'
    line: 'command[check{{ item.key }}_disk]=/usr/lib/nagios/plugins/check_disk -w {{ item.value.warning }}% -c {{ item.value.critical }}% -p {{ item.value.path }}'
  with_dict: "{{ check_disk }}"
  notify:
    - restart nrpe

- name: Write additionals nrpe commands to /etc/nagios/nrpe_local.cfg
  lineinfile: dest=/etc/nagios/nrpe_local.cfg regexp={{ item.value.regexp }} line={{ item.value.line }}
  with_dict: "{{ nrpe_checks | default({}) }}"
  notify:
    - restart nrpe
