---
- name: Install transmission package
  ansible.builtin.apt:
    name: transmission-daemon
    state: present
  register: transmission_installed
  until: transmission_installed is success
  retries: 10
  delay: 2

- name: Stop transmission during configuration
  ansible.builtin.service:
    name: transmission-daemon
    state: stopped
  changed_when: false

- name: Install /etc/transmission-daemon/settings.json
  ansible.builtin.template:
    src: etc/transmission-daemon/settings.json.j2
    dest: /etc/transmission-daemon/settings.json
    owner: debian-transmission
    group: debian-transmission
    mode: "0600"
  no_log: true

- name: Start transmission
  ansible.builtin.service:
    name: transmission-daemon
    state: started
  changed_when: false
