---
- name: Create admin group
  ansible.builtin.group:
    name: admin
    gid: 10000
    state: present

- name: Create user accounts
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    comment: "{{ item.comment }}"
    groups: "{{ item.groups }}"
    shell: "{{ item.shell }}"
  with_items: "{{ users }}"

- name: Create ~/.profile
  ansible.builtin.template:
    src: profile.j2
    dest: /home/{{ item.name }}/.profile
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0644"
  with_items: "{{ users }}"

- name: Create ~/.bashrc
  ansible.builtin.template:
    src: bashrc.j2
    dest: /home/{{ item.name }}/.bashrc
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0644"
  with_items: "{{ users }}"

- name: Add user ssh key
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_key }}"
  with_items: "{{ users }}"
  when: item.state == 'present'

- name: Create sudo file for admin group
  ansible.builtin.template:
    src: etc/sudoers.d/admin.j2
    dest: /etc/sudoers.d/admin
    validate: visudo -cf %s
    owner: root
    group: root
    mode: "0644"
