---
- name: Update /etc/vim/vimrc
  ansible.builtin.template:
    src: etc/vim/vimrc.j2
    dest: /etc/vim/vimrc
    owner: root
    group: root
    mode: "0644"

- name: Remove this shitty mouse support in vim
  ansible.builtin.replace:
    path: /usr/share/vim/vim82/defaults.vim
    regexp: set mouse=a
    replace: set mouse-=a
    mode: "0644"
    owner: root

- name: Set vim as default editor
  community.general.alternatives:
    name: editor
    path: /usr/bin/vim.basic
