---
# Users
users:
  - name: kmet
    comment: 'Kevin MET'
    groups: admin
    shell: /bin/bash
    state: present
    ssh_key: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDch7PXOqVis44PiH6/WmfyukAAEpbNwv6Teh69mr3mgHSKQVEjawSxx/04R/zF4dK7DkTOF4F5w18Lf5e4T8i6uKxyyFfDn3kyo9aTm2wsJJ9Dd3bKTieqEPv+nm7W2ExZ1U+zE9WH5vxjn4eYHSgLjxcsk+hreY7dgqAeswVkzRpXutgZR6qVI4jR37zBXy6i9i+IFDV5veMWJf4GPx7VHgdfbzgUvfP+/LLs9uGf/l0KyLidwF5cMc9gKBJf0ta4xll/WqrsJWjDK6YAhzpnxmnUt5/bIsvZpPmoJk36oAh2wrPwYhXGogg5oygwh7/LB/N0dIg0rNE3LKjx+orqWWvFkHSII+rXpl4ulUFDhpmBTq8+w0jpIa2zh4JfByTtiogIfTSe/0zab8mokbbWuveNbmb2T/uKBoSb9Zhrba1GZbQxlT12q6eJdLFJypJACENBmEHgt67/m6ToJx62v+dkVcqrfaHWZ+F64P2JJ7NnucIWwLZo/Z6t2dqfCps= nierdz@precisux
      ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzODQAAABhBFhOPgv2mw/KZh852AczFWFjmV5+/1vqEg4xqKNZTGpHwb3OIYcFjav8NE4Vo03LHjZKefiIF7MdPB/zBcxeVlNIc4rZwoiL/GO3mpdacpOBsNZRX2cav8DRsVZYQNKJVw== nierdz@oneplus5

# PHP
php_default_version_debian: "7.4"
php_packages:
  - php7.4-common
  - php7.4-cli
  - php7.4-dev
  - php7.4-fpm
  - libpcre3-dev
  - php7.4-gd
  - php7.4-curl
  - php7.4-imap
  - php7.4-json
  - php7.4-opcache
  - php7.4-xml
  - php7.4-mbstring
  - php-sqlite3
  - php-imagick

# Nginx
nginx_remove_default_vhost: true
nginx_service_enabled: true
nginx_service_state: started
nginx_user: nginx
nginx_pidfile: /run/nginx.pid

# BackupPC
backuppc_server: backup.atelierasap.com

# Certbot
certbot_create_if_missing: true
certbot_create_standalone_stop_services: []
certbot_auto_renew: false # renew is already done by a cron inside certbot package
certbot_create_command: >-
  {{ certbot_script }} certonly
    --non-interactive
    --email "{{ cert_item.email }}"
    --agree-tos
    --dns-ovh
    --dns-ovh-credentials /infra/.ovh
    --post-hook "{{ cert_item.post_hook }}"
    --domains "{{ cert_item.domains | join(',') }}"
