---
# Users
users:
  - name: kmet
    comment: 'Kevin MET'
    groups:
      - admin
    shell: /bin/bash
    state: present
    ssh_key: https://github.com/nierdz.keys

# BackupPC
backuppc_server: backup.atelierasap.com
