---
- name: Install backuppc packages
  apt:
    name:
      - backuppc
      - fcgiwrap
      - libfile-rsyncp-perl
      - python-passlib
    state: present
  register: backuppc_packages_installed
  until: backuppc_packages_installed is success
  retries: 10
  delay: 2

- name: Disable apache2 service
  systemd:
    name: apache2
    state: stopped
    enabled: false

- name: Create htpasswd file
  htpasswd:
    path: /etc/nginx/backuppc.htpasswd
    name: backuppc
    password: "{{ backuppc_password }}"
    owner: root
    group: nginx
    mode: 0640
