---
- name: Import setup tasks
  import_tasks: setup.yml

- name: Import pre configure tasks
  import_tasks: pre-configure.yml

- name: Import update tasks
  import_tasks: update.yml

- name: Import post configure tasks
  import_tasks: post-configure.yml

- name: Find old releases
  find:
    paths: "{{ nextcloud_releases_path }}"
    age: "{{ nextcloud_keep_releases }}"
    file_type: directory
    recurse: no
  register: old_releases

- name: Register current release
  find:
    paths: "{{ nextcloud_releases_path }}"
    file_type: directory
    recurse: no
    patterns: "{{ nextcloud_git_branch }}"
  register: current_release

- name: Delete old releases
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ old_releases.files | difference(current_release.files) }}"
