---
- name: Set correct permissions
  file:
    path: "{{ nextcloud_deploy_to }}"
    state: directory
    recurse: yes
    owner: nginx
    group: nginx

- name: Run occ upgrade
  command: "/usr/bin/php occ upgrade"
  become: true
  become_user: nginx
  args:
    chdir: "{{ nextcloud_deploy_to }}/{{ nextcloud_current_dir }}"
  when: symlink_update is changed

- name: Run occ maintenance:repair
  command: "/usr/bin/php occ maintenance:repair"
  become: true
  become_user: nginx
  args:
    chdir: "{{ nextcloud_deploy_to }}/{{ nextcloud_current_dir }}"
  when: symlink_update is changed

- name: Run occ maintenance:mode --off
  command: "/usr/bin/php occ maintenance:mode --off"
  become: true
  become_user: nginx
  args:
    chdir: "{{ nextcloud_deploy_to }}/{{ nextcloud_current_dir }}"
  when: symlink_update is changed
