---
- name: Create .ocdata file in data folder if needed
  copy:
    content: ""
    dest: /var/www/data/.ocdata
    force: no
    group: "{{ nginx_user }}"
    owner: "{{ nginx_user }}"
    mode: 0644

- name: Run occ upgrade
  command: "/usr/bin/php occ upgrade"
  become: true
  become_user: "{{ nginx_user }}"
  args:
    chdir: "{{ nextcloud_deploy_to }}/{{ nextcloud_current_dir }}"
  when: symlink_update is changed or config_update is changed

- name: Run occ maintenance:repair
  command: "/usr/bin/php occ maintenance:repair"
  become: true
  become_user: "{{ nginx_user }}"
  args:
    chdir: "{{ nextcloud_deploy_to }}/{{ nextcloud_current_dir }}"
  when: symlink_update is changed or config_update is changed

- name: Restart php-fpm
  service:
    name: php7.3-fpm
    state: restarted
  when: symlink_update is changed or config_update is changed

- name: Creates a cron file under /etc/cron.d
  cron:
    name: nextcloud
    minute: "*/5"
    user: "{{ nginx_user }}"
    job: "/usr/bin/php -f {{ nextcloud_deploy_to }}/{{ nextcloud_current_dir }}/cron.php"
    cron_file: nextcloud
