---
- name: Install php modules
  apt:
    name: "{{ nextcloud_php_packages }}"
    state: present
    update_cache: true
  register: php_packages_installed
  until: php_packages_installed is success
  retries: 10
  delay: 2

- name: Install unzip
  apt:
    name: unzip
    state: present
    update_cache: true
  register: unzip_installed
  until: unzip_installed is success
  retries: 10
  delay: 2

- name: Install redis packages
  apt:
    name:
      - redis-server
      - redis-tools
    state: present
    update_cache: true
  register: redis_installed
  until: redis_installed is success
  retries: 10
  delay: 2
