---
- name: Ensure deployment base path exists
  file:
    state: directory
    path: "{{ nextcloud_deploy_to }}"

- name: Ensure releases folder exists
  file:
    state: directory
    path: "{{ nextcloud_releases_path }}"

- name: Ensure shared elements folder exists
  file:
    state: directory
    path: "{{ nextcloud_shared_path }}"

- name: Ensure shared paths exists
  file:
    state: directory
    path: "{{ nextcloud_shared_path }}/{{ item }}"
  with_items: "{{ nextcloud_shared_paths }}"

- name: Ensure basedir shared files exists
  file:
    state: directory
    path: "{{ nextcloud_shared_path }}/{{ item | dirname }}"
  with_items: "{{ nextcloud_shared_files }}"
