---
- name: Check if nextcloud {{ nextcloud_git_branch }} already exists
  stat:
    path: "{{ nextcloud_releases_path }}/nextcloud_git_branch"
  register: nextcloud_release

- name: Clone nextcloud git repository if release does not exist
  git:
    repo: "{{ nextcloud_git_repo }}"
    dest: "{{ nextcloud_releases_path }}/{{ nextcloud_git_branch }}"
    version: "{{ nextcloud_git_branch }}"
    update: yes
    force: yes
    accept_hostkey: yes
  become: true
  become_user: "{{ nginx_user }}"
  register: git_update
  when: not nextcloud_release.stat.exists

- name: Check nextcloud version # noqa 303
  command: sed -rn "s/.*VersionString = '(.*)';/v\1/p" "{{ nextcloud_releases_path }}/{{ nextcloud_git_branch }}/version.php"
  register: version
  failed_when: version.stdout != nextcloud_git_branch
  changed_when: false

- name: Check nextcloud long version
  shell: |
    set -o pipefail
    sed -rn "s/.*Version = array\((.*)\);/\1/p" "{{ nextcloud_releases_path }}/{{ nextcloud_git_branch }}/version.php" | sed "s/, /./g"
  register: version_long
  changed_when: false

- name: Install nextcloud config.php
  template:
    src: config/config.php.j2
    dest: "{{ nextcloud_shared_path }}/config/config.php"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: 0640
