- name: Install percona repository package
  ansible.builtin.apt:
    deb: "https://repo.percona.com/apt/percona-release_latest.{{ ansible_distribution_release }}_all.deb"

- name: Install percona packages
  apt:
    name: "{{ percona_packages }}"
    state: present
    update_cache: true
  register: percona_packages_installed
  until: percona_packages_installed is success
  retries: 10
  delay: 2
