---
- name: Create mysql backup folder
  file: path=/opt/scripts/mysql state=directory owner=root group=root mode=0755

- name: Copy backup.sh to /opt/scripts/mysql
  template: src=backup.sh.j2 dest=/opt/scripts/mysql/backup.sh owner=root group=root mode=0700

- name: Copy backup.conf to /opt/scripts/mysql
  template: src=backup.conf.j2 dest=/opt/scripts/mysql/backup.conf owner=root group=root mode=0600

- name: Install nsca-ng-client package
  apt: name=nsca-ng-client cache_valid_time=86400 state=latest

- name: Configure /etc/send_nsca.cfg
  template: src=send_nsca.cfg.j2 dest=/etc/send_nsca.cfg owner=root group=root mode=0644

- name: Define mysql backup in /etc/crontab
  lineinfile:
    dest: /etc/crontab
    line: "00 1 * * *	root	cd /opt/scripts/mysql && ./backup.sh"
  notify:
    - cron restart

- name: Add MYSQL_BACKUP service in {{ mnttech_fqdn }}.cfg
  delegate_to: "{{ nagios_fqdn }}"
  blockinfile:
    dest: /etc/icinga/servers/{{ mnttech_fqdn }}.cfg
    marker: "# {mark} ANSIBLE : MYSQL_BACKUP service"
    block: |
      define service {
        use             		mysql-backup-services
        host_name           	{{ mnttech_fqdn }}
        service_description     MYSQL_BACKUP
        check_command           mysql_backup!2!"CRITICAL{{":"}} no passive check received in the last 24 hours"
      }
