---
- name: Check if variable mysql is defined to prevent error
  debug: msg={{ mysql }}
  when: mysql

- name: Add percona apt key if needed
  apt_key: keyserver=keys.gnupg.net id=8507EFA5
  when: mysql_version == "percona"

- name: Add percona.list if needed
  apt_repository: repo="deb http://repo.percona.com/apt {{ ansible_distribution_release }} main" state=present filename="percona"
  when: mysql_version == "percona"

- name: Ensure MySQL packages are installed
  apt: "name={{ item }} cache_valid_time=86400 state=present"
  with_items: "{{ mysql_packages }}"

- name: Ensure MySQL Python libraries are installed
  apt: "name=python-mysqldb state=present"

- include: configure.yml

- include: users.yml
  static: no
  when: mysql_users is defined

- include: backup.yml
- include: nrpe.yml
