---
- name: Create nagios user
  mysql_user: name=nagios password={{ lookup('password', 'passwords/' + mnttech_fqdn + '/mysql_nagios_password.txt') }} priv='*.*:SELECT,REPLICATION CLIENT' host=localhost state=present

- name: Nagios MySQL password
  set_fact: mysql_nagios_password={{ lookup('file', 'passwords/' + mnttech_fqdn + '/mysql_nagios_password.txt') }}

- name: Write mysql_health commands to /etc/nagios/nrpe_local.cfg
  lineinfile: dest=/etc/nagios/nrpe_local.cfg regexp={{ item.regexp }} line={{ item.line }}
  with_items:
    - { regexp: '^command\[check_mysql_conn\]=.*check_mysql_health.*\-\-mode connection\-time', line: 'command[check_mysql_conn]=/usr/lib/nagios/plugins/check_mysql_health --hostname localhost --username nagios --password "{{ mysql_nagios_password }}" --mode connection-time' }
    - { regexp: '^command\[check_mysql_threads\]=.*check_mysql_health.*\-\-mode threads\-connected.*', line: 'command[check_mysql_threads]=/usr/lib/nagios/plugins/check_mysql_health --hostname localhost --username nagios --password "{{ mysql_nagios_password }}" --mode threads-connected --warning {{ check_mysql_threads.warning }} --critical {{ check_mysql_threads.critical }}' } 
  notify:
    - restart nrpe

- name: Write check_mysql commands to /etc/nagios/nrpe_local.cfg if needed
  when: mysql_check_slave is defined and mysql_check_slave
  lineinfile: dest=/etc/nagios/nrpe_local.cfg regexp={{ item.regexp }} line={{ item.line }}
  with_items:
    - { regexp: '^command\[check_mysql_slave\]=.*check_mysql.*\-S', line: 'command[check_mysql_slave]=/usr/lib/nagios/plugins/check_mysql --hostname localhost --username nagios --password "{{ mysql_nagios_password }}" -S' }
  notify:
    - restart nrpe

- name: Add MYSQL CONN services in {{ mnttech_fqdn }}.cfg
  delegate_to: "{{ nagios_fqdn }}"
  blockinfile:
    dest: /etc/icinga/servers/{{ mnttech_fqdn }}.cfg
    marker: "# {mark} ANSIBLE : MYSQL CONN service"
    block: |
      define service {
      	use				{{ nagios_type }}-services
      	host_name			{{ mnttech_fqdn }}
      	service_description		MYSQL CONN
      	check_command			check_nrpe!check_mysql_conn
      }

- name: Add MYSQL THREAD services in {{ mnttech_fqdn }}.cfg
  delegate_to: "{{ nagios_fqdn }}"
  blockinfile:
    dest: /etc/icinga/servers/{{ mnttech_fqdn }}.cfg
    marker: "# {mark} ANSIBLE : MYSQL THREAD service"
    block: |
      define service {
      	use				{{ nagios_type }}-services
      	host_name			{{ mnttech_fqdn }}
      	service_description		MYSQL THREAD
      	check_command			check_nrpe!check_mysql_threads
      }

- name: Add MYSQL SLAVE services in {{ mnttech_fqdn }}.cfg
  delegate_to: "{{ nagios_fqdn }}"
  when: mysql_check_slave is defined and mysql_check_slave
  blockinfile:
    dest: /etc/icinga/servers/{{ mnttech_fqdn }}.cfg
    marker: "# {mark} ANSIBLE : MYSQL SLAVE service"
    block: |
      define service {
      	use				{{ nagios_type }}-services
      	host_name			{{ mnttech_fqdn }}
      	service_description		MYSQL SLAVE
      	check_command			check_nrpe!check_mysql_slave
      }
