---
- name: Check if variable proftpd is defined to prevent error
  debug: msg={{ proftpd }}
  when: proftpd

- name: Proftpd package installation
  apt: name={{ item }} cache_valid_time=86400 state=latest
  with_items:
    - proftpd-basic

- name: Support utf8
  lineinfile: dest=/etc/default/proftpd line='export LANG=en_US.UTF-8'
  notify:
    - proftpd restart

- name: Chroot user
  replace: dest=/etc/proftpd/proftpd.conf regexp='^# DefaultRoot.*' replace='DefaultRoot ~'
  notify:
    - proftpd restart

- name: Set umask to 027
  replace: dest=/etc/proftpd/proftpd.conf regexp='^Umask.*022.*022$' replace='Umask 027 027'
  notify:
    - proftpd restart
