---
- name: Import OVH tasks
  import_tasks: ovh.yml

- name: Install common packages
  become: true
  apt:
    name: "{{ common_packages }}"
    state: present
  register: common_packages_installed
  until: common_packages_installed is success
  retries: 10
  delay: 2

- name: Install other packages
  apt:
    name: "{{ other_packages|default([]) }}"
    state: present
  register: other_packages_installed
  until: other_packages_installed is success
  retries: 10
  delay: 2

- name: Set localtime to Europe/Paris
  timezone:
    name: Europe/Paris

- name: Better history
  template:
    src: etc/profile.d/history.sh.j2
    dest: /etc/profile.d/history.sh
    owner: root
    group: root
    mode: 0755

- name: Add some aliases
  template:
    src: etc/profile.d/alias.sh.j2
    dest: /etc/profile.d/alias.sh
    owner: root
    group: root
    mode: 0755

- name: Define logrotate in /etc/crontab
  lineinfile:
    dest: /etc/crontab
    line: "00 0	* * *	root  /usr/sbin/logrotate /etc/logrotate.conf"
  notify:
    - cron restart

- name: Clean old logrotate script in /etc/cron.daily/logrotate
  template:
    src: etc/cron.daily/logrotate.j2
    dest: /etc/cron.daily/logrotate
    owner: root
    group: root
    mode: 0755

- name: Change PS1
  lineinfile:
    dest: /etc/bash.bashrc
    regexp: "^export PS1.*"
    line: 'export PS1="\[\033[38;5;51m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\[$(tput sgr0)\]\[\033[38;5;208m\]$(hostname -f)\[$(tput sgr0)\]\[\033[38;5;15m\]:\w \\$ \[$(tput sgr0)\]"'

- name: Install crontab entries
  cron:
    name: "{{ item.key }}"
    backup: "{{ item.value.backup     | default('no') }}"
    day: "{{ item.value.day           | default('*') }}"
    hour: "{{ item.value.hour         | default('*') }}"
    job: "{{ item.value.job           | default()}}"
    minute: "{{ item.value.minute     | default('*') }}"
    month: "{{ item.value.month       | default('*') }}"
    state: "{{ item.value.state       | default('present') }}"
    user: "{{ item.value.user         | default('root') }}"
    weekday: "{{ item.value.weekday   | default('*') }}"
    disabled: "{{ item.value.disabled | default('no') }}"
  with_dict: "{{crontabs | default({})}}"

- name: Import vim tasks
  import_tasks: vim.yml

- name: Import users tasks
  import_tasks: users.yml
