---
- name: Ensure deployment base path exists
  file:
    state: directory
    path: "{{ nextcloud_deploy_to }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: 0755

- name: Ensure releases folder exists
  file:
    state: directory
    path: "{{ nextcloud_releases_path }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: 0755

- name: Ensure shared elements folder exists
  file:
    state: directory
    path: "{{ nextcloud_shared_path }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: 0755

- name: Ensure shared paths exists
  file:
    state: directory
    path: "{{ nextcloud_shared_path }}/{{ item }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: 0755
  with_items: "{{ nextcloud_shared_paths }}"

- name: Ensure basedir shared files exists
  file:
    state: directory
    path: "{{ nextcloud_shared_path }}/{{ item | dirname }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: 0755
  with_items: "{{ nextcloud_shared_files }}"
