---

- name: cron restart
  service:
    name: cron
    state: restarted

- name: apt update
  apt: update_cache=true
  register: cache_updated
  until: cache_updated is success
  retries: 10
  delay: 2

- name: postfix restart
  service:
    name: postfix
    state: restarted
