---
- name: Check if variable apache-php-fpm is defined to prevent error
  debug: msg={{ apache_php_fpm }}
  when: apache_php_fpm

- name: Install dependencies for Ondrej repo
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Add Ondrej Sury's apt key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: Add Ondrej Sury's repo
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present
  register: php_ondrej_repo

- name: Update apt caches after repo is added
  apt: update_cache=true
  when: php_ondrej_repo.changed

- name: Install apache2
  apt: name={{ item }} cache_valid_time=86400 state=latest
  with_items:
    - apache2

- name: Install php7 packages if needed
  when: php_version == "7"
  apt:
    name:
      - php7.3-fpm
      - php7.3-curl
      - php7.3-redis
      - php7.3-mysql
      - php7.3-xml
      - php7.3-gd
      - php7.3-mbstring
      - php7.3-intl
      - php7.3-zip
      - php7.3-imagick
    cache_valid_time: 86400
    state: latest

- include: configuration.yml
- include: php-fpm.yml
- include: vhosts.yml
