---
- name: Install metricbeat
  apt:
    name: "metricbeat={{ metricbeat_version }}"
    state: present
    update_cache: true
  register: metricbeat_installed
  until: metricbeat_installed is success
  retries: 10
  delay: 2

- name: Check if metricbeat keystore already exists
  stat:
    path: /var/lib/metricbeat/metricbeat.keystore
  register: metricbeat_keystore

- name: Create the keystore if it doesn't exist yet
  command: >
    /usr/bin/metricbeat
    keystore create
  when: not metricbeat_keystore.stat.exists

- name: Check if metricbeat password is already stored
  command: >
    /usr/bin/metricbeat
    keystore list
  register: metricbeat_keystore_list
  changed_when: false

- name: Store metricbeat password if needed
  shell: >
    set -o pipefail &&
    echo {{ metricbeat_password }} |
    /usr/bin/metricbeat
    keystore add METRICBEAT_PASSWORD
    --stdin --force
  when: '"METRICBEAT_PASSWORD" not in metricbeat_keystore_list.stdout'
