baseURL = "/"
languageCode = "fr-fr"
DefaultContentLanguage = "fr"
title = "IGLN"
theme = "docdock"
enableRobotsTXT = true
enableEmoji = true
pygmentsCodeFences = true
pygmentsStyle = "monokailight"
[Languages]
  [Languages.fr]
    title = "IGLN"
    weight = 1
    languageName = "Français"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
author = "Kévin Met"
sharingicons = false
themeStyle = "original"
ordersectionsby = "weight"
disableHomeIcon = true

[[menu.shortcuts]]
pre = "<h3>À propos</h3>"
name = "<i class='fa fa-github'></i> <label>github</label>"
identifier = "ds"
url = "https://github.com/nierdz"
weight = 10

[[menu.shortcuts]]
name = "<i class='fa fa-linkedin'></i> <label>linkedin</label>"
url = "https://www.linkedin.com/in/kmet/"
weight = 11
