languageCode = "fr-fr"
DefaultContentLanguage = "fr"
title = "IGLN"
theme = "hugo-theme-bootstrap4-blog"
enableRobotsTXT = true
enableEmoji = true
paginate = 10
copyright = "coucou, c'est la fin de la page ! Fait avec [hugo](https://gohugo.io/)"

[permalinks]
  posts = "/:slug/"
  page = "/:slug/"

[params]
  author = "Kévin Met"
  description = "💩 mon petit merdier sur l'internet 💩"
  date_format = "02 Mon Jan 2006"
  sharingicons = false

  [params.sidebar]
    about = "Mon bordel très rarement mis à jour."
    num_recent_posts = 5

  [params.social]
    twitter = "nierdz_"

[languages.fr]
