- name: Provision all servers
  become: true
  hosts: all
  roles:
    - { role: utils, tags: ['utils'] }
    - { role: bind, tags: ['bind'] }
  post_tasks:
    - name: Remove /etc/sudoers.d/kmet
      file:
        path: /etc/sudoers.d/kmet
        state: absent
    - meta: reset_connection

- name: Provision xmr-stak
  become: true
  hosts: xmrstak
  roles:
    - { role: xmr_stak, tags: ['xmr_stak'] }

- name: Provision hypervisors
  become: true
  hosts: docker
  vars_files:
    - vault_vars/all.yml
  pre_tasks:
    - name: Clone infra repository
      git:
        repo: git@github.com:nierdz/infra.git
        version: "master"
        dest: /infra
        accept_hostkey: true
        track_submodules: true
        update: false
    - name: Create /infra/.env
      template:
        src: vault_files/docker.env
        dest: /infra/.env
        mode: 0400
        owner: root
        group: root
    - name: Create certbot directory
      file:
        path: /infra/certbot
        state: directory
        mode: 0755
        owner: root
        group: root
  roles:
    - { role: docker, tags: ['docker'] }
    - { role: certbot, tags: ['certbot'] }
    - { role: mysql_backup, tags: ['mysql_backup'] }

- name: Configure ip failover
  become: true
  hosts: physical
  roles:
    - { role: ip_failover, tags: ['ip_failover'] }

- name: Configure nextcloud servers
  become: true
  hosts: nextcloud
  vars_files:
    - vault_vars/all.yml
  # First nginx will only create a vhost for certbot
  # Then, second one will create actual vhost
  roles:
    - { role: nginx, tags: ['nginx'], dummy: 'first' }
    - { role: certbot, tags: ['certbot'] }
    - { role: nginx, tags: ['nginx'], dummy: 'second' }
    - { role: mysql, tags: ['mysql'] }
    - { role: php, tags: ['php'] }
    - { role: percona, tags: ['percona'] }
    - { role: nextcloud, tags: ['nextcloud'] }
    - { role: mysql_backup, tags: ['mysql_backup'] }
  pre_tasks:
    - name: Install sury key
      apt_key:
        url: "https://packages.sury.org/php/apt.gpg"
        state: present
    - name: Add sury repositories
      apt_repository:
        repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes
        filename: 'sury'

- name: Provision transmission
  become: true
  hosts: srv1.igln.fr
  vars_files:
    - vault_vars/transmission.yml
  roles:
    - { role: transmission, tags: ['transmission'] }

- name: Provision backuppc
  become: true
  hosts: backup.atelierasap.com
  vars_files:
    - vault_vars/all.yml
  roles:
    - { role: nginx, tags: ['nginx'], dummy: 'first' }
    - { role: certbot, tags: ['certbot'] }
    - { role: nginx, tags: ['nginx'], dummy: 'second' }
    - { role: backuppc, tags: ['backuppc'] }
