---
- src: geerlingguy.php
  version: 4.6.1
  name: php

- src: geerlingguy.mysql
  version: 3.3.2
  name: mysql

- src: geerlingguy.docker
  version: 3.1.2
  name: docker

- src: geerlingguy.nginx
  version: 3.1.0
  name: nginx

- src: nierdz.nextcloud
  version: 21.0.2
  name: nextcloud
