---
- src: geerlingguy.php
  version: 5.0.1
  name: php

- src: geerlingguy.mysql
  version: 4.3.4
  name: mysql

- src: geerlingguy.docker
  version: 6.1.0
  name: docker

- src: geerlingguy.nginx
  version: 3.1.4
  name: nginx

- src: https://github.com/nierdz/ansible-role-nextcloud
  version: 27.1.3
  name: nextcloud

- src: arillso.logrotate
  version: 1.6.1
  name: logrotate
