---
- src: geerlingguy.php
  version: 4.8.0
  name: php

- src: geerlingguy.mysql
  version: 4.2.0
  name: mysql

- src: geerlingguy.docker
  version: 6.0.3
  name: docker

- src: geerlingguy.nginx
  version: 3.1.3
  name: nginx

- src: nierdz.nextcloud
  version: 25.0.2
  name: nextcloud

- src: arillso.logrotate
  version: 1.6.1
  name: logrotate
