---
- name: Add dotdeb apt key if needed
  apt_key: keyserver=keys.gnupg.net id=89DF5277
  when: php_repo == "dotdeb"

# Hack le temps que dotdeb passe sur stretch
- name: Add dotdeb.list if needed
  apt_repository: repo="deb http://packages.dotdeb.org {{ ansible_distribution_release }} all" state=present filename='dotdeb'
  when: php_repo == "dotdeb" and ansible_distribution_release != "stretch"
- name: Add dotdeb.list if needed
  apt_repository: repo="deb http://packages.dotdeb.org jessie all" state=present filename='dotdeb'
  when: php_repo == "dotdeb" and ansible_distribution_release == "stretch"

- name: Install nginx
  apt: name={{ item }} cache_valid_time=86400 state=latest default_release={{ ansible_distribution_release }}
  with_items:
    - nginx

- name: Install php7 if needed
  when: php_version == "7"
  apt: name={{ item }} cache_valid_time=86400 state=latest
  with_items:
    - php7.0-fpm
    - php7.0-curl
    - php7.0-redis
    - php7.0-mysql
    - php7.0-xml
    - php7.0-gd
    - php7.0-mbstring
    - php7.0-intl
    - php7.0-zip

- include: configuration.yml
- include: php-fpm.yml
- include: vhosts.yml
