---
- name: Install certbot
  apt:
    name: certbot
    state: present
    update_cache: true
  register: certbot_installed
  until: certbot_installed is success
  retries: 10
  delay: 2

- include_tasks: manage-cert.yml
  with_items: "{{ certbot_certs }}"
