name: CI

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt install -y python3-pip python3-virtualenv
    - name: install check tools
      run: make install
    - name: run all checks
      run: make tests
  build:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: start on fresh docker installation
      run: docker system prune --all --force --volumes
    - name: build all images
      run: make build
