---
name: CI

on: push

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install dependencies
        run: python -m pip install --upgrade pip virtualenv
      - name: install check tools
        run: make install
      - name: run pre-commit
        run: make pre-commit
      - name: run ansible-lint
        run: make ansible-lint
