name: CI

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt install -y python-pip python-virtualenv
    - name: install check tools
      run: make install
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: start on fresh docker installation
      run: docker system prune --all --force --volumes
    - name: build all images
      run: make build
