name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: start on fresh docker installation
      run: docker system prune --all --force --volumes
    - name: build all images
      run: make build
