name: CI

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: install dependencies
      run: python -m pip install --upgrade pip virtualenv
    - name: install check tools
      run: make install
    - name: run all checks
      run: make tests
  build-push:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: start on fresh docker installation
      run: docker system prune --all --force --volumes
    - name: build all images
      run: make build
    - name: push images on docker hub if necessary
      run: bash scripts/docker-push.sh
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
