---
name: DOCKER-BUILD

on:
  push:
    paths:
    - 'docker/*/Dockerfile'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: start on fresh docker installation
      run: docker system prune --all --force --volumes
    - name: build all docker images
      run: make docker-build
