---
name: GIST-SYNC

on:
  push:
    branches:
      - master

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: igln-1
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/nierdz/20ee8324932d19b036b26d5b24c61245
          gist_title: Dockerfile
          gist_description: Dockerfile for igln.fr
          github_file: docker/igln.fr/Dockerfile
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: igln-2
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/nierdz/0fa0dae5d7a55f3d6960881d663a35b2
          gist_title: docker-compose-igln.yml
          gist_description: docker-compose for igln.fr
          github_file: docker-compose-igln.yml
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: igln-3
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/nierdz/a9392c8586350b6f1d31c78aee16f2ff
          gist_title: docker-push.sh
          gist_description: script to push all my docker images to docker hub
          github_file: scripts/docker-push.sh
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: igln-4
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/nierdz/d433dcb98457d343ec51986005edd538
          gist_title: docker-push.yml
          gist_description: github actions jobs to push all my docker images to docker hub
          github_file: .github/workflows/docker-push.yml
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: igln-5
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/nierdz/07469cc4d744615f6cb9335210cf2942
          gist_title: docker-build.sh
          gist_description: script to build all my docker images
          github_file: scripts/docker-build.sh
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: igln-6
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/nierdz/6952539552b9ac9c8b6e93c0065b9a16
          gist_title: wordpress-bulk-delete-custom-fields.sh
          gist_description: script to bulk delete custom post fields on WordPress
          github_file: scripts/wordpress-bulk-delete-custom-fields.sh
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: igln-7
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/nierdz/ca180f3f05d6ee445743d4685fae5359
          gist_title: wordpress-check-duplicate-custom-fields.sh
          gist_description: script to check for duplicate custom fields on WordPress
          github_file: scripts/wordpress-check-duplicate-custom-fields.sh
