---
name: RELEASE

on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    steps:
      - name: Build Changelog
        id: git-chglog
        run: |
          curl -o /usr/local/bin/git-chglog -L https://github.com/git-chglog/git-chglog/releases/download/0.10.0/git-chglog_linux_amd64
          chmod +x /usr/local/bin/git-chglog
          tag=`basename ${{ github.ref }}`
          changelog="$(/usr/local/bin/git-chglog ${tag})"
          echo "::set-output name=changelog::${changelog}"
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.git-chglog.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
